import '~/styles/globals.css';

import { type Metadata } from 'next';

import Providers from '~/components/Providers';
import { ClerkProvider } from '@clerk/nextjs';

export const metadata: Metadata = {
  title: 'Next Todo',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className="bg-[url('/grid.svg')]">
          <Providers attribute="class" defaultTheme="system" enableSystem>
            {children}
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
};

export default RootLayout;
