import '~/styles/globals.css';

import { ClerkProvider } from '@clerk/nextjs';

import { type Metadata } from 'next';
import { Inter } from 'next/font/google';

import Providers from '~/components/Providers';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Next Todo',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en" className={inter.className} suppressHydrationWarning>
      <body>
        <ClerkProvider>
          <Providers attribute="class" defaultTheme="dark">
            {children}
          </Providers>
        </ClerkProvider>
      </body>
    </html>
  );
};

export default RootLayout;
